name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget
  
jobs:
  build-pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack HybridCache/HybridCache.csproj --no-build -c Release -o ${{ env.NuGetDirectory }}
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          if-no-files-found: error
          retention-days: 1
          path: ${{ env.NuGetDirectory }}/*.nupkg
          
  validate-pkg:
    runs-on: ubuntu-latest
    needs: [ build-pkg ]
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.*'

      - uses: actions/download-artifact@v3
        with:
          name: nuget-packages
          path: ${{ env.NuGetDirectory }}

      - name: Install nuget validator
        run: dotnet tool update Meziantou.Framework.NuGetPackageValidation.Tool --global

      - name: Validate NuGet Package
        run: meziantou.validate-nuget-package ${{ env.NuGetDirectory }}/*.nupkg --rules AssembliesMustBeOptimized
        
  publish-pkg:
    runs-on: ubuntu-latest
    needs: [ validate-pkg ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nuget-packages
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.*'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Package
        run: dotnet nuget push ${{ env.NuGetDirectory }}/*.nupkg --no-symbols --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}